{ statuses: 
   [ { created_at: 'Sat Feb 10 20:56:25 +0000 2018',
       id: 962430076540383200,
       id_str: '962430076540383232',
       full_text: 'Aelwaer’s Cat https://t.co/sJ4OiktrKx',
       truncated: false,
       display_text_range: [ 0, 37 ],
       entities: 
        { hashtags: [],
          symbols: [],
          user_mentions: [],
          urls: 
           [ { url: 'https://t.co/sJ4OiktrKx',
               expanded_url: 'https://goo.gl/fb/nZXWB5',
               display_url: 'goo.gl/fb/nZXWB5',
               indices: [ 14, 37 ] } ] },
       metadata: { iso_language_code: 'cy', result_type: 'recent' },
       source: '<a href="http://www.google.com/" rel="nofollow">Google</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: 
        { id: 21908767,
          id_str: '21908767',
          name: 'Michael Broad',
          screen_name: 'Michael_Broad',
          location: 'London, England',
          description: 'I am passionate about cat welfare 🐈. I am retired but quite busy working on my website and other things. I love cats, animals, photography, the landscape.',
          url: 'http://t.co/WXl1B4wYkz',
          entities: 
           { url: 
              { urls: 
                 [ { url: 'http://t.co/WXl1B4wYkz',
                     expanded_url: 'http://pictures-of-cats.org/',
                     display_url: 'pictures-of-cats.org',
                     indices: [ 0, 22 ] } ] },
             description: { urls: [] } },
          protected: false,
          followers_count: 182,
          friends_count: 143,
          listed_count: 3,
          created_at: 'Wed Feb 25 19:48:19 +0000 2009',
          favourites_count: 7,
          utc_offset: 0,
          time_zone: 'London',
          geo_enabled: true,
          verified: false,
          statuses_count: 5659,
          lang: 'en',
          contributors_enabled: false,
          is_translator: false,
          is_translation_enabled: false,
          profile_background_color: 'D4B087',
          profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/116244407/7_Maine_Coon_Kittens.jpg',
          profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/116244407/7_Maine_Coon_Kittens.jpg',
          profile_background_tile: true,
          profile_image_url: 'http://pbs.twimg.com/profile_images/892361069569740800/P7XfEuks_normal.jpg',
          profile_image_url_https: 'https://pbs.twimg.com/profile_images/892361069569740800/P7XfEuks_normal.jpg',
          profile_banner_url: 'https://pbs.twimg.com/profile_banners/21908767/1435321553',
          profile_link_color: 'ABB8C2',
          profile_sidebar_border_color: 'E3A97F',
          profile_sidebar_fill_color: 'DDE8C3',
          profile_text_color: '333333',
          profile_use_background_image: true,
          has_extended_profile: true,
          default_profile: false,
          default_profile_image: false,
          following: false,
          follow_request_sent: false,
          notifications: false,
          translator_type: 'none' },
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 0,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'cy' } ],
  search_metadata: 
   { completed_in: 0.017,
     max_id: 962430076540383200,
     max_id_str: '962430076540383232',
     next_results: '?max_id=962430076540383231&q=cat%20pictures%20exclude%3Aretweets&count=1&include_entities=1',
     query: 'cat+pictures+exclude%3Aretweets',
     refresh_url: '?since_id=962430076540383232&q=cat%20pictures%20exclude%3Aretweets&include_entities=1',
     count: 1,
     since_id: 0,
     since_id_str: '0' 
   } 
 }